name: Update Donation Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths-ignore:
      - 'data/donations.json'  # Don't trigger on donation data changes to avoid loops

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel any in-progress runs

jobs:
  update-data:
    # Skip if commit message contains [skip ci] or [ci skip]
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set a timeout to prevent hung jobs
    permissions:
      contents: write  # Gives permission to push to the repository
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic GITHUB_TOKEN
        fetch-depth: 0  # Fetch all history for git operations
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Node.js dependencies
      run: npm ci
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright beautifulsoup4 requests
        playwright install chromium
        
    - name: Run scraper
      run: |
        # Add retries for network issues
        for i in {1..3}; do
          if python scraper.py; then
            break
          fi
          echo "Attempt $i failed, retrying..."
          sleep 10
        done
      
    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet data/donations.json || echo "changes=true" >> $GITHUB_OUTPUT
      
    - name: Commit data changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/donations.json
        git commit -m "Update donation data [skip ci]"
        git push
        
    - name: Setup Node.js
      if: steps.check_changes.outputs.changes == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install website dependencies
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        npm ci --production --prefer-offline
        npm install gh-pages --no-save  # Install gh-pages for deployment
        
    - name: Build and deploy website
      if: steps.check_changes.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Add retries for deployment
        for i in {1..3}; do
          if npm run deploy -- -u "github-actions-bot <support+actions@github.com>" -m "Deploy website [skip ci]"; then
            break
          fi
          echo "Deployment attempt $i failed, retrying..."
          sleep 10
        done
