name: Update Donation Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-js: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Run scraper
      run: node scraper.js
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/donations.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update donation data [skip ci]" && git push)
