name: Update Donation Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Gives permission to push to the repository
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic GITHUB_TOKEN
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright beautifulsoup4 requests
        playwright install chromium
        
    - name: Run scraper
      run: python scraper.py
      
    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet data/donations.json || echo "changes=true" >> $GITHUB_OUTPUT
      
    - name: Commit data changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/donations.json
        git commit -m "Update donation data [skip ci]"
        git push
        
    - name: Setup Node.js
      if: steps.check_changes.outputs.changes == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install website dependencies
      if: steps.check_changes.outputs.changes == 'true'
      run: npm install
        
    - name: Build and deploy website
      if: steps.check_changes.outputs.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        npm run deploy
